### ISSUE TITLE
Security vulnerability at i5k.github.io

### ISSUE THREAD

**Issue by monicacecilia** [i5k/i5k.github.io#10]
Hello @childers @mpoelchau 
I just saw this from a couple hours ago. Do you guys think one of you can have a look and update?

- Known critical severity security vulnerability detected in nokogiri < 1.8.1defined in Gemfile.lock:
```Gemfile.lock update suggested: nokogiri ~> 1.8.1.```

- Known high severity security vulnerability detected in yajl-ruby < 1.3.1 defined in Gemfile.lock:
```Gemfile.lock update suggested: yajl-ruby ~> 1.3.1.```

To review these vulnerable dependencies, go to https://github.com/i5k/i5k.github.io/network/dependencies

**Comment by monicacecilia** [comment]
neverrrrmiiiiiiind - @childers was already on it way before I wrote this issue!  
Thanks Chris!!

**Comment by childers** [comment]
This should be resolved.  If you see any issues, reopen this and I'll get it squared.
