### ISSUE TITLE
Another jekyll issue

### ISSUE THREAD

**Issue by childers** [i5k/i5k.github.io#6]
It was working, but now I get the following error.  Manually installing this module doesn't fix the issue.

Your bundle is locked to json (1.8.3), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed
sources, that means the author of json (1.8.3) has removed it. You'll need to update your bundle to a different version of json (1.8.3) that hasn't
been removed in order to install.

**Comment by childers** [comment]
ok, after a LOT of wrangling, it is working now.  It seems to break on every pull/fetch. Is anyone else having that issue?

**Comment by monicacecilia** [comment]
Rats. Sounds very inconvenient. Just letting you know I haven't come across this ... yet.

**Comment by childers** [comment]
Honestly, I'm glad it is just me. It seems like every time I do a pull, something resets. Hopefully my last round of configuration adjustments will stick.
